In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cu124


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Recebe o tensor novamente como um inteiro em python
scalar.item()

7

In [ ]:
#Vetor
vetor = torch.tensor([7,7])
vetor


tensor([7, 7])

In [ ]:
vetor.ndim

1

In [ ]:
vetor.shape

torch.Size([2])

In [ ]:
#Matriz
matriz = torch.tensor([[7 , 8],
                       [9 , 10]])
matriz

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matriz.ndim

2

In [ ]:
matriz[0]

tensor([7, 8])

In [ ]:
matriz[1]

tensor([ 9, 10])

In [ ]:
matriz.shape

torch.Size([2, 2])

In [ ]:
#Tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,8]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 8]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

##Tensors aleatórios


###Por que tensors aleatórios?
Eles sao importantes porque a maneira que algumas redes neurais aprendem começa com tensors cheios de números aleatórios e eles ajustam esses números aleatórios para representarem de uma forma melhor os dados.

```
# Isto está formatado como código
```



In [ ]:
#criando um tensor aleatório de tamanho (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.6180, 0.6443, 0.5259, 0.7313],
        [0.2082, 0.6107, 0.3916, 0.2537],
        [0.5127, 0.5902, 0.6525, 0.6561]])

In [ ]:
#Criar um tensor com uma estrutura similar a um tensor de uma imagem
random_image_size_tensor = torch.rand(size =(224,224,3)) #Altura, larguras e canais de cores(RGB)
random_image_size_tensor.shape , random_image_size_tensor.ndim



(torch.Size([224, 224, 3]), 3)

### Zeros e Uns


In [ ]:
#Criar um tensor só de zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Criar um tensor só de Uns
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Como cirar uma faixa de valores (range) de tensors

In [ ]:
#Usar torch.arange()
one_to_ten = torch.arange(start = 1,step = 1 , end = 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
Tensor datatypes é um dos 3 grandes erros que você vai cometer no Pytorch e no deep learning


1. Tensors com o datatype errado
2. Tensors com o shape errado
3. Tensors no device errado





In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #Qual tipo de dado é esse tensor (e.g float32 ou float16)
                               device = None, #Em qual device esta o tensor
                               requires_grad = False) # Se deve ou não rastrear gradientes durante essas operações com tensors

float_32_tensor


tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Conseguir informações de tensors
1. Tensors com o datatype errado - para descobrir o datatype se usa 'tensor.dtype'
2. Tensors com o shape errado - para descobrir o shape se usa 'tensor.shape'
3. Tensors no device errado - para descobrir em qual device o tensor está, se usa 'tensor.device'

In [ ]:
tensor  = torch.rand (3,4)
tensor


tensor([[0.6090, 0.5589, 0.0416, 0.2122],
        [0.3740, 0.5796, 0.2500, 0.4781],
        [0.7517, 0.8904, 0.9190, 0.6238]])

In [ ]:
tensor.dtype

torch.float32

In [ ]:
tensor.shape

torch.Size([3, 4])

In [ ]:
tensor.device

device(type='cpu')

### Manipulando tensors (operações de tensors)
Operações de tensors incluem:
* Adição
* Subtração
* Multiplicação
* Divisão
* Multiplicação de matrizes

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 1

tensor([0, 1, 2])

In [ ]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

### Multiplicação de matriz
Duas maneira de fazer uma multiplicação em redes neurais e deep learning:
1. Elemento a elemento
2. Multiplicação de matriz

In [ ]:
#Elemento a elemento
tensor*tensor

tensor([1, 4, 9])

In [ ]:
#Multiplicação de matriz
torch.matmul(tensor, tensor)

tensor(14)

### Um dos erros mais comuns em deep learning: shape error

In [ ]:
#Shapes for matrix multiplicatio
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

Para concertar o shape de um tensor, podemos manipular o shape de um tensor utilizando *transpose*

In [ ]:
tensor_B.T

In [ ]:
#A multiplicação de matriz funciona quando o tensor_B é transposto
torch.matmul(tensor_A, tensor_B.T)

Finding the min, max, mean, sum, etc (tensor agregation)

In [ ]:
#Crate a tensor
x = torch.arange(0,100,10)
x

In [ ]:
#Find the min
torch.min(x)

In [ ]:
#Find the max
torch.max(x)

In [ ]:
#Find the mean - note: the torch.mean function requires a tensor of float32 to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

#Finding de position min and max

In [ ]:
x

In [ ]:
#Find the position in tensor that has the minimum value with argmin()
x.argmin()

In [ ]:
#Find the position in tensor that has the maximun value with argmax()
x.argmax()


In [ ]:
x[9]

#Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep teh same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
#Creaat a tensor
import torch
x = torch.arange(1,10)
x, x.shape

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

In [ ]:
#Changing z changes x (beacause a view of a tensor shares the same memory as the original input)

z[:,0] = 5
z,x

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

In [ ]:
#torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

In [ ]:
#Unsqueeze
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

In [ ]:
x_reshaped.squeeze()

In [ ]:
x_reshaped.squeeze().shape

In [ ]:
#torch.permute
x_original = torch.rand(size=(224,224,3))
#Permute the original tensor to rearange the axis (or dim) order
x_permuted = x_original.permute(2,0,1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

## Indexing (selecting data from tensor)
Indexing with pytorch is similar to indexing with numpy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

In [ ]:
#Let's index on our new tensor
x[0]

In [ ]:
#Let's index in the middle bracket (dim = 1)
x[0][0]

In [ ]:
#Let's index on the most inner bracket (last dimension)
x[0][0][0]

In [ ]:
#You can also use ":" to select "all" of a target dimension
x[:,0]

In [ ]:
# Get all values of 0th and 1st dimensionss but only index 1 of 2nd dimension
x[:,:,1]

In [ ]:
x[:,2,:]

##Pytorch tensors and NumPy
* Data in Numpy, want in PyTorch tensor -> 'torch.form_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
 #NumPy array to tensor
 import numpy as np

 array = np.arange(1.0,8.0)
 tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's datatype of float64 unless specified otherwise
 array , tensor

In [ ]:
# Change the value of array, what  will this do to 'tensor'?
array = array +1
array, tensor

In [ ]:
#tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

In [ ]:
#change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor


## Reproducbility (trying to take random out of random)
In short how a neural network learns:
`starts with random numbers -> tensor operations -> update random numbers to try and make better representations of the data -> again ->again ->again ...`

To reduce the randomness in neural networks and PyTorch comes to concept of a **random seed**.
Essentially wath the random seed does is a "flavour" the randomness.



In [ ]:
#create two random tensors
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand (3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)


In [ ]:
# Let's make some random but reproducible tensors
# Set the random seed
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

##Running tensors and pytorch objects on the GPUs (and making faster computations)
GPUs = Faster computation on numbers


### 1. Getting a GPU
1. Easiest - Use google colab for a free GPU
2. Use your oun GPU
3. Use cloud computing - (GCP, AWS, Azure)


In [ ]:
!nvidia-smi


### 2. Check for GPU access with PyTorch

In [ ]:
#Chech for GPU access with PyTorch
import torch
torch.cuda.is_available()



In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

In [ ]:
#Count number of devices
torch.cuda.device_count()

## 3. Putting tensor (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
#Create a tensor
tensor = torch.tensor([1,2,3])
#Tensor not on GPU
print(tensor, tensor.device)

In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

## 4. Moving tensors back to the CPU


In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu