# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch


# Create random tensor
tensor = torch.rand(7,7)
tensor


tensor([[0.0983, 0.2144, 0.7080, 0.2019, 0.9090, 0.1211, 0.5195],
        [0.8817, 0.6142, 0.5598, 0.9890, 0.6879, 0.7715, 0.9745],
        [0.4186, 0.8496, 0.8129, 0.0305, 0.9560, 0.3251, 0.5556],
        [0.7168, 0.2700, 0.4188, 0.8099, 0.3621, 0.0743, 0.0274],
        [0.0956, 0.9826, 0.7966, 0.4547, 0.7050, 0.0140, 0.8962],
        [0.0859, 0.8686, 0.6765, 0.2114, 0.1866, 0.0918, 0.1960],
        [0.2805, 0.8448, 0.1290, 0.7419, 0.8465, 0.5679, 0.7271]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_2 = torch.rand(1,7)

# Perform matrix multiplication
print(f"Tensor 1: {tensor}")
print(f"\nTensor 2: {tensor_2}")
print(f"\nTensor X Tensor = {tensor*tensor_2}")





Tensor 1: tensor([[0.0983, 0.2144, 0.7080, 0.2019, 0.9090, 0.1211, 0.5195],
        [0.8817, 0.6142, 0.5598, 0.9890, 0.6879, 0.7715, 0.9745],
        [0.4186, 0.8496, 0.8129, 0.0305, 0.9560, 0.3251, 0.5556],
        [0.7168, 0.2700, 0.4188, 0.8099, 0.3621, 0.0743, 0.0274],
        [0.0956, 0.9826, 0.7966, 0.4547, 0.7050, 0.0140, 0.8962],
        [0.0859, 0.8686, 0.6765, 0.2114, 0.1866, 0.0918, 0.1960],
        [0.2805, 0.8448, 0.1290, 0.7419, 0.8465, 0.5679, 0.7271]])

Tensor 2: tensor([[0.2317, 0.6191, 0.2776, 0.6693, 0.4040, 0.6018, 0.1259]])

Tensor X Tensor = tensor([[0.0228, 0.1327, 0.1965, 0.1351, 0.3673, 0.0729, 0.0654],
        [0.2043, 0.3802, 0.1554, 0.6619, 0.2779, 0.4643, 0.1227],
        [0.0970, 0.5259, 0.2256, 0.0204, 0.3863, 0.1957, 0.0700],
        [0.1661, 0.1671, 0.1162, 0.5421, 0.1463, 0.0447, 0.0035],
        [0.0222, 0.6083, 0.2211, 0.3044, 0.2848, 0.0085, 0.1129],
        [0.0199, 0.5377, 0.1878, 0.1415, 0.0754, 0.0553, 0.0247],
        [0.0650, 0.5230, 0.0358, 0

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
torch.manual_seed(0)
torch_rand1 = torch.rand(7,7)
torch.manual_seed(0)
torch_rand2 = torch.rand(1,7)


# Matrix multiply tensors
print(f"Tensor 1: {torch_rand1}")
print(f"\nTensor 2: {torch_rand2}")
print(f"\nTensor X Tensor = {torch_rand1*torch_rand2}")


Tensor 1: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

Tensor 2: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

Tensor X Tensor = tensor([[0.2463, 0.5902, 0.0078, 0.0174, 0.0945, 0.4021, 0.2402],
        [0.4449, 0.3500, 0.0559, 0.0461, 0.1235, 0.0142, 0.0828],
        [0.1458, 0.3983, 0.0617, 0.1056, 0.0495, 0.1790, 0.3341],
        [0.4542, 0.3051, 0.0773, 0.0554, 0.1700, 0.6041, 0.0177],
        [0.0919, 0.2869, 0.0270, 0.1231, 0.0541, 0.1711, 0.0738],
        [0.0157, 0.1599, 0.0823, 0.0955, 0.2282, 0.3337, 0.1194],
        [0.2901, 0.0255, 0.0123, 0

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
random_seed = 1234
torch.manual_seed(random_seed)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)




# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
rand_tensor = torch.rand(2,3)
rand_tensor2 = torch.rand(2,3)
x = rand_tensor.to(device)
y = rand_tensor2.to(device)

print(f"Device : {device}")
print(x)
print(y)


Device : cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
reshaped_tensor = y.reshape(3,2)
z = torch.matmul(x,reshaped_tensor)
print(z,z.shape)




tensor([[0.4759, 0.2931],
        [0.6074, 0.5855]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(torch.max(z))
# Find min
print(torch.min(z))


tensor(0.6074, device='cuda:0')
tensor(0.2931, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max

print(torch.argmax(z))

# Find arg min
print(torch.argmin(z))


tensor(2, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)


# Create random tensor
tensor = torch.rand(1,1,1,10)


# Remove single dimensions
x = torch.squeeze(tensor)

# Print out tensors and their shapes
print(f"Previous tensor: {tensor}")
print(f"Presvious shape: {tensor.shape}")
print(f"New tensor: {x}")
print(f"New shape: {x.shape}")


Previous tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Presvious shape: torch.Size([1, 1, 1, 10])
New tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
New shape: torch.Size([10])
